#!/bin/sh

# Load terminal helpers
. "$(dirname "$0")/terminal.sh"

INFO "Checking commit message."


if ! npx commitlint -e ; then

    ERROR "Commit message not allowed."    
    exit 1

fi


DONE "Commit Done."
