#!/bin/sh
# shellcheck source=/dev/null

set -e

# Check the commit message

## Move to rootdir
cd "$(git rev-parse --show-toplevel)" || exit 1

## Load terminal helpers
. Library/Software/Terminal/bootstrap.sh

INFO "Checking commit message."

if ! npx commitlint -e ; then

    ERROR "Commit message not allowed."    
    exit 1

fi


DONE "Commit Done."
