#!/bin/sh
# shellcheck source=/dev/null

# Lint and verify staged files

set -e


## Move to rootdir
cd "$(git rev-parse --show-toplevel)" || exit 1

## Load terminal helpers
. Library/Software/Terminal/bootstrap.sh

## Load environment variables

if test -f ./.env; then
    . ./.env
fi

## Execute lint on changed files

INFO "Running lint in changed files."

if ! (npx lint-staged && git update-index --again); then

    if [[ $GIT_HOOK_CHECK_CONTINUE_WHEN_FAIL -eq 0 ]]; then
        FATAL "Failed to execute lint in changed files."
        exit 1
    fi
fi

DONE "Lint executed."
